# Generated by Django 4.1.7 on 2023-04-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
