# Generated by Django 4.1.7 on 2023-04-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_ingredient_description_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Alcohol'), (2, 'Mixer'), (3, 'Garnish')], default=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
